<?php
/** @var $next Posting_Row */
$next = !empty($this->entries['next']) ? $this->entries['next'] : null;
/** @var $prev Posting_Row */
$prev = !empty($this->entries['prev']) ? $this->entries['prev'] : null;
if (!empty($next) || !empty($prev)) {
?>
<ul class="adjacent">
<?php if (!empty($prev)) { ?>
    <li class="prev"><a href="<?php echo $this->url($prev->getRouteParameters(), $prev->getRouteName(), true); ?>" title="<?php echo $this->escape($prev->getTitle()); ?>">Предыдущая запись</a></li>
<?php } ?>
<?php if (!empty($next)) { ?>
    <li class="next"><a href="<?php echo $this->url($next->getRouteParameters(), $next->getRouteName(), true); ?>" title="<?php echo $this->escape($next->getTitle()); ?>">Следующая запись</a></li>
<?php } ?>
</ul>
<?php
}
?>