<?php if ($this->entry->isPublic()) { ?>
<div class="addthis-container">
    <!-- AddThis Button BEGIN -->
    <a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;username=ozgg"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0" /></a>
    <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=ozgg"></script>
    <!-- AddThis Button END -->
</div>
<?php } ?>

<?php
if (!empty($this->canComment)) {
?>
<div id="reply-main">
    <div class="header" onclick="$('#reply-main-form').toggle();">Добавить комментарий</div>
    <form id="reply-main-form" action="<?php echo $this->url(array('id' => $this->entry->getId()), 'posting_comments_create', true); ?>" method="post">
        <dl>
            <?php
            if (!empty($this->avatars)) {
                ?>
                <dt><label for="main-comment-avatar-id">Картинка пользователя</label></dt>
                <dd>
                    <select name="avatar_id" id="main-comment-avatar-id">
                        <option value="0">Не выбрана</option>
                        <?php
                        $format = "\t\t\t\t<option value=\"%u\"%s>%s</option>\n";
                        /** @var $avatar User_Avatar_Row */
                        foreach ($this->avatars as $avatar) {
                            $selected = '';
                            if ($this->formData['avatarId'] == $avatar->getId()) {
                                $selected = ' selected="selected"';
                            }
                            printf($format, $avatar->getId(), $selected, $avatar->getName());
                            unset($avatar, $selected);
                        }
                        unset($format);
                        ?>
                    </select>
                </dd>
                <dd class="notice">Эта картинка будет сопровождать комментарий.</dd>
                <?php
            }
            ?>
            <dt><label for="main-body">Текст комментария</label></dt>
            <dd><textarea name="body" id="main-body" cols="30" rows="10"></textarea></dd>
        </dl>
        <div class="submit"><button type="submit">Добавить</button></div>
    </form>
</div>
<script type="text/ecmascript">
    $.ready = function() {
    $('#reply-main-form').toggle();
    }
</script>
<?php
}

$comments = $this->entry->getComments();
if (!empty($comments)) {

?>
<div id="comments">
    <h3>Комментарии (<?php echo count($comments); ?>)</h3>
    <ul>
        <?php
        $level  = 0;
        $stripe = 1;
        /** @var $comment Posting_Comment_Row */
        foreach ($comments as $comment) {
            $commentId = $comment->getId();
            $owner     = $comment->getOwner();
            $ownerLink = $this->partial('user/_userlink.phtml', array(
                'login' => $owner->getLogin(false)
            ));
            $date = Ext_Helper_Date::makeString($comment->getCreatedAt(), true);
            $class = '';
            if ($stripe++ > 0) {
                $class  = ' stripe1';
                $stripe = 0;
            }
            $body = BodyParser::parseEntry($comment->getBody(), array(BodyParser::OPTION_ESCAPE => true));
            ?>
            <li id="comment-<?php echo $commentId; ?>" class="comment" style="margin-left: <?php echo ($comment->getLevel() - 1) * 3; ?>em">
                <div class="header<?php echo $class; ?>">
                    <div class="avatar"><?php echo $comment->getAvatar(); ?></div>
                    <div class="spawn-info">
                        <?php echo "{$date}<br />\n"; ?>
                        <?php echo $ownerLink; ?>
                    </div>
                </div>
                <div class="body">
                    <?php echo $body['body']; ?>
                </div>
                <div class="footer" id="comment-footer-<?php echo $commentId; ?>">
                    <div class="comment-options">
                        (<a href="#comment-<?php echo $commentId; ?>">ссылка</a>)
                    </div>
                    <?php
                    if (!empty($this->canComment)) {
                        ?>
                        <div class="answer-button" onclick="moveAnswerForm(<?php echo $commentId; ?>)">
                            Ответить
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </li>
            <?php
        }
        ?>
    </ul>
    <?php
    if (!empty($this->canComment)) {
        ?>
        <form id="answer-form" action="<?php echo $this->url(array('id' => $this->entry->getId()), 'posting_comments_create', true); ?>" method="post" style="display: none">
            <dl>
                <?php
                if (!empty($this->avatars)) {
                    ?>
                    <dt><label for="answer-comment-avatar-id">Картинка пользователя</label></dt>
                    <dd>
                        <select name="avatar_id" id="answer-comment-avatar-id">
                            <option value="0">Не выбрана</option>
                            <?php
                            $format = "\t\t\t\t<option value=\"%u\"%s>%s</option>\n";
                            foreach ($this->avatars as $avatar) {
                                $selected = '';
                                if ($this->formData['avatarId'] == $avatar->getId()) {
                                    $selected = ' selected="selected"';
                                }
                                printf($format, $avatar->getId(), $selected, $avatar->getName());
                                unset($avatar, $selected);
                            }
                            unset($format);
                            ?>
                        </select>
                    </dd>
                    <dd class="notice">Эта картинка будет сопровождать комментарий.</dd>
                    <?php
                }
                ?>
                <dt><label for="answer-body">Текст ответа</label></dt>
                <dd><textarea name="body" id="answer-body" cols="30" rows="10"></textarea></dd>
            </dl>
            <div class="submit"><button type="submit">Ответить на комментарий</button></div>
            <div><input type="hidden" name="parent_id" value="" id="answer-parent" /></div>
        </form>
        <?php
    }
    ?>
</div>
<?php
} else {
    echo '<div class="result">Нет ни одного комментария</div>';
}
?>