<?php
$href = $this->url(array('id' => $this->entry->getId(), 'alias' => $this->entry->getAlias()), $this->entry->getRouteName());
$isInternal = $this->entry->getIsinternal();
$lockString = '';
if ($isInternal > 0) {
    switch ($isInternal) {
        case 1:
            $title = ' title="Видно только зарегистрированным пользователям"';
            break;
        case 255:
            $title = ' title="Видно только автору"';
            break;
        default:
            $title = '';
    }
    $lockString = '<div class="lock-' . $isInternal . '"' . $title . '>&nbsp;</div>';
}
$options = array(BodyParser::OPTION_ESCAPE => !$this->entry->isArticle());
$body = BodyParser::parseEntry($this->entry->getBody());
?>
<div class="entry">
    <div class="header">
        <div class="avatar"><?php echo $this->partial('user/_avatar.phtml', array('avatar' => $this->entry->getAvatar())); ?></div>
        <div class="spawn-info">
            <?php echo $this->partial('user/_userlink.phtml', array('login' => $this->entry->getOwner()->getLogin())); ?>,
            <?php echo $this->entry->getDate(); ?>
        </div>
        <div class="title"><?php echo $lockString; ?><a href="<?php echo $href; ?>" title="Читать"><?php echo $this->escape($this->entry->getTitle()); ?></a> (<?php echo $this->entry->getType()->getName(); ?>)</div>
    </div>
    <div class="entry-body"><?php echo BodyParser::replaceCuts($body['body'], $href); ?></div>
    <div class="entry-footer"><a href="<?php echo $href; ?>" title="Ссылка на эту запись">Ссылка</a></div>
</div>