<?php
$href       = $this->url(array('id' => $this->entry->getId(), 'alias' => $this->entry->getAlias()), $this->route);
$isInternal = $this->entry->getIsinternal();
$options    = array(BodyParser::OPTION_ESCAPE => !$this->entry->isArticle());
$body       = BodyParser::parseEntry($this->entry->getBody(), $options);
?>
<div class="entry">
    <div class="header">
        <div class="avatar"><?php echo $this->partial('user/_avatar.phtml', array('avatar' => $this->entry->getAvatar())); ?></div>
        <div class="spawn-info">
            <?php echo $this->partial('user/_userlink.phtml', array('login' => $this->entry->getOwner()->getLogin())); ?>,
            <?php echo $this->entry->getDate(); ?>
        </div>
        <div class="title">
<?php if ($isInternal > 0) { ?>
            <div class="lock-<?php echo $isInternal; ?>" title="Ограничение видимости">&nbsp;</div>
<?php } ?>
<?php if ($this->isPreview) { ?>
            <a href="<?php echo $href; ?>" title="Читать"><?php echo $this->escape($this->entry->getTitle()); ?></a>
            (<?php echo $this->entry->getType()->getName(); ?>)
<?php } else { ?>
            <?php echo $this->escape($this->entry->getTitle()); ?>
<?php } ?>
        </div>
    </div>
    <div class="entry-body"><?php echo $body['body']; ?></div>
    <div class="entry-footer"><a href="<?php echo $href; ?>" title="Ссылка на эту запись">Ссылка</a></div>
</div>