<?php
$href = $this->url(array('id' => $this->entry->getId(), 'alias' => $this->entry->getAlias()), $this->route);
?>
<div class="entry">
    <div class="header">
        <div class="avatar"><?php echo $this->partial('user/_avatar.phtml', array('avatar' => $this->entry->getAvatar())); ?></div>
        <div class="spawn-info">
            <?php echo $this->partial('user/_userlink.phtml', array('login' => $this->entry->getOwner()->getLogin())); ?>,
            <?php echo $this->entry->getDate(); ?>
        </div>
        <div class="title"><?php echo $this->escape($this->entry->getTitle()); ?></div>
    </div>
    <div class="entry-body"><?php echo $this->entry->getBody(); ?></div>
    <div class="entry-footer"><a href="<?php echo $href; ?>" title="Ссылка на эту запись">Ссылка</a></div>
</div>