<?php
$isInternal = $this->entry->getIsinternal();
$options    = $this->entry->getParserOptions();
$parsedBody = BodyParser::parseEntry($this->entry->getBody(), $options);
$href       = $this->url($this->entry->getRouteParameters(), $this->entry->getRouteName());

if ($this->isPreview) {
    $body = BodyParser::replaceCuts($parsedBody['preview'], $href);
} else {
    $body = $parsedBody['body'];
}
?>
<article class="entry">
    <header>
        <div class="avatar"><?php echo $this->partial('user/_avatar.phtml', array('avatar' => $this->entry->getAvatar())); ?></div>
        <div class="spawn-info">
            <?php echo $this->partial('user/_userlink.phtml', array('login' => $this->entry->getOwner()->getLogin())); ?>,
            <?php echo Ext_Helper_Date::makeString($this->entry->getCreatedAt(), true); ?>
        </div>
        <div class="title">
<?php if ($isInternal > 0) { ?>
            <div class="lock-<?php echo $isInternal; ?>" title="Ограничение видимости">&nbsp;</div>
<?php } ?>
<?php if ($this->isPreview) { ?>
            <a href="<?php echo $href; ?>" title="Читать"><?php echo $this->escape($this->entry->getTitle()); ?></a>
            (<?php echo $this->entry->getType()->getName(); ?>)
<?php } else { ?>
            <?php echo $this->escape($this->entry->getTitle()); ?>
<?php } ?>
        </div>
        <?php echo $this->partial('posting/_tags.phtml', array('tags' => $this->entry->getTags(), 'route' => $this->entry->getTagRoute(), 'tagLinks' => !$this->isPreview)); ?>
    </header>
    <div class="body"><?php echo $body; ?></div>
    <footer>
        <a href="<?php echo $href; ?>" title="Ссылка на эту запись">Ссылка</a>
<?php if ($this->isPreview) { ?>
    <span class="comments-link">
        <a href="<?php echo $href; ?>#comments" title="Посмотреть комментарии">
            <?php echo Ext_Helper_Declension::decline($this->entry->getHasComments(), array('комментариев', 'комментарий', 'комментария')); ?>
        </a>
    </span>
<?php } ?>
    </footer>
</article>
