<?php
if (!empty($this->tags) && !empty($this->route)) {
?>
<div class="tags">
    Метки:
<?php
    $links = array();
    foreach ($this->tags as $tag) {
        /** @var $tag Posting_Tag_Row */
        $tagLink = '<a href="' . $this->url(array('tag' => $tag->getName()), $this->route) . '" rel="tag">' . $this->escape($tag->getName()) . '</a>';
        if (!empty($this->tagLinks)) {
            $post    = $tag->getPost();
            if (!empty($post)) {
                $tagLink .= ' (<a href="' . $this->url($post->getRouteParameters(), $post->getRouteName()) . '" title="Толкование">?</a>)';
            }
        }
        $links[] = $tagLink;
    }
    echo implode(', ', $links);
?>
</div>
<?php
}
?>
