<h1>Сущности сна</h1>
<h2>Страница <?php echo $this->page; ?></h2>

<?php if ($this->page < 2) { ?>
<h3>Что такое сущности сна?</h3>
<p>Сущности во сне — это в основном персонажи сна, но к ним также можно отнести
    и отдельные объекты, а иногда даже целые куски местности. Поэтому в общем
    случае мы будем описывать здесь всё, про что можно будет сказать при описании
    «это сущность».</p>
<?php } ?>

<?php if ($this->isActive) { ?>
<p><a href="<?php echo $this->url(array(), 'entities_new', true); ?>">Описать сущность</a></p>
<?php } ?>

<?php echo $this->partial('posting/_entries.phtml', array('entries' => $this->entries)); ?>

<?php echo $this->paginator; ?>