<?php if (!empty($this->crumbs)) {
?>
<div id="breadcrumbs">
	<span><a href="<?php echo $this->url(array(), 'home', true); ?>" title="На главную">Совия</a></span>
<?php
foreach ($this->crumbs as $link => $text) {
	if (!is_int($link)) {
		if ($link[0] != '/') {
			$link  = "/{$link}";
		}
		if ($link[strlen($link) - 1] != '/') {
			$link .= '/';
		}
		echo "\t<span> &raquo; <a href=\"{$link}\">{$text}</a></span>\n";
	} else {
		echo "\t<span> &raquo; {$text}</span>\n";
	}
}
unset($link, $text);
?>
</div>
<?php
}
?>
