<h1>Статьи</h1>

<?php if ($this->canEdit) { ?>
<p><a href="<?php echo $this->url(array('id' => $this->entry->getId()), 'articles_edit_entry', true); ?>" title="Редактировать">Редактировать</a></p>
<?php } ?>

<?php echo $this->partial('posting/_adjacent.phtml', array('entries' => $this->adjacent)); ?>

<?php echo $this->partial('posting/_entry.phtml', array('entry' => $this->entry)); ?>

<?php
echo $this->partial('posting/_comments.phtml', array(
    'entry'      => $this->entry,
    'avatars'    => $this->avatars,
    'avatarId'   => $this->avatarId,
    'canComment' => $this->canComment
));
?>
