<aside class="auth">
<?php
if ($this->user->getId() > 0) {
	$link  = $this->partial('user/_userlink.phtml', array('login' => $this->user->login));
?>
    <header>Здравствуйте, <?php echo $link; ?>.</header>
    <nav>
        <ul>
            <li><a href="<?php echo $this->url(array(), 'cabinet', true); ?>">Кабинет</a></li>
            <li><a href="<?php echo $this->url(array(), 'user_logout', true); ?>">Выйти</a></li>
        </ul>
    </nav>
<?php
} else {
?>
    <form id="auth-top" method="post" action="<?php echo $this->url(array(), 'user_login', true); ?>">
    <dl>
        <dt><label for="auth-login-top"><a href="<?php echo $this->url(array(), 'user_login', true); ?>" title="Вход">Вход</a> на сайт: </label></dt>
        <dd><input type="text" size="16" maxlength="16" id="auth-login-top" name="login" title="Логин" placeholder="Логин" /></dd>
        <dd><input type="password" size="14" id="auth-password-top" name="password" title="Пароль" placeholder="Пароль" /></dd>
        <dd><input type="image" src="/images/auth-submit.gif" id="auth-submit-top" title="Войти" /><input type="hidden" name="remember" value="1" /></dd>
    </dl>
    </form>
    <ul id="auth-options">
        <li><a href="<?php echo $this->url(array(), 'user_register', true); ?>">Регистрация</a></li>
        <li><a href="<?php echo $this->url(array(), 'user_forgot', true); ?>">Забыли пароль?</a></li>
    </ul>
<?php
}
?>
</aside>
