<?php
$login = '';
if (!empty($this->user)) {
	$login = $this->user->getLogin();
?>
<h2>Профиль пользователя <?php echo $login; ?></h2>
<p>Дата регистрации на сайте: <?php echo $this->user->getCreatedAt(); ?></p>
<p>Последний раз на сайте: <?php echo $this->user->getLastSeen(); ?></p>
<p>Сообщений: <?php echo $this->user->getHasPosts(); ?></p>
<p>Комментариев: <?php echo $this->user->getHasComments(); ?></p>
<p><a href="<?php echo $this->url(array('login' => $this->user->getLogin()), 'dreams_author', true); ?>/">Читать сны этого пользователя</a></p>
<?php
} else {
	if ($this->search != '') {
		$login = $this->search;
	}
?>
<h3>Найти пользователя</h3>
<form id="user-profile-search" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'profile'), null, true); ?>" method="post">
<dl>
	<dt><label for="search-login">Логин пользователя</label></dt>
	<dd><input type="text" name="search_login" id="search-login" value="<?php echo $this->escape($login); ?>" size="16" maxlength="16" /></dd>
</dl>
<div class="submit"><button type="submit">Найти</button></div>
</form>
<?php	if ($this->search != '') { ?>
<h3>Результаты поиска по запросу &laquo;<?php echo $this->escape($this->search); ?>&raquo;</h3>
<?php		if (!empty($this->list)) { ?>
<ul id="profile-found-users">
<?php			foreach ($this->list as $user) { ?>
	<li><?php echo $this->partial('user/_userlink.phtml', array('login' => $user->getLogin())); ?></li>
<?php			}
				unset($login); ?>
</ul>
<?php		} else { ?>
<div class="result">Ничего не найдено</div>
<?php		} ?>
<?php	} ?>
<?php } ?>
<p><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'profile'), null, true); ?>">Найти другого пользователя</a></p>
