<!-- SpyLOG -->
<script src="http://tools.spylog.ru/counter_cv.js" id="spylog_code" type="text/javascript" counter="857572" part="" track_links="ext" page_level="<?php echo intval($_SERVER['REQUEST_URI'] != '/'); ?>"></script>
<noscript>
    <div>
        <a href="http://u8575.72.spylog.com/cnt?cid=857572&amp;f=3&amp;p=0" target="_blank">
            <img src="http://u8575.72.spylog.com/cnt?cid=857572&amp;p=<?php echo intval($_SERVER['REQUEST_URI'] != '/'); ?>" alt="SpyLOG" width="88" height="31" />
        </a>
    </div>
</noscript>
<!--/ SpyLOG -->

<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    var pageTracker = _gat._getTracker("UA-6037428-1");
    pageTracker._trackPageview();
</script>