<p>Здравствуйте, <?php echo $this->user->getLogin(); ?>.</p>
<p>Для сброса вашего пароля проследуйте по ссылке
    <a href="<?php echo $this->route; ?>"><?php echo $this->_route; ?></a> и введите
    ключ <b><?php echo $this->key->getBody(); ?></b></p>
<p>Если вы не запрашивали восстановление пароля, просто проигнорируйте это письмо.</p>
<p>-- <br />
    С уважением,<br />
    Команда sovia.ru</p>
