<?php if (!empty($this->words)) { ?>
<div class="divider"></div>
<ul class="dreambook-list">
<?php foreach ($this->words as $item) { ?>
    <li>
        <a href="<?php echo $this->url(array('letter' => $item['letter'], 'symbol' => $item['title']), 'dreambook_entry', true); ?>" title="Значение символа"><?php echo $this->escape($item['title']); ?></a>
    </li>
<?php    } ?>
</ul>
<div class="divider"></div>
<?php } ?>