<h1>Сонник</h1>

<?php echo $this->action('letters', 'dreambook'); ?>

<?php if ($this->canEdit) { ?>
<p><a href="<?php echo $this->url(array('id' => $this->entry->getId()), 'dreambook_edit_entry', true); ?>" title="Редактировать">Редактировать</a></p>
<?php } ?>

<?php echo $this->partial('posting/_entry.phtml', array('entry' => $this->entry)); ?>

<?php
echo $this->partial('posting/_comments.phtml', array(
    'entry'      => $this->entry,
    'avatars'    => $this->avatars,
    'canComment' => $this->canComment
));
?>
