<?php
echo $this->doctype() . PHP_EOL;
?>
<html>
<head>
<?php
echo $this->headMeta() . PHP_EOL;
echo $this->headLink() . PHP_EOL;
echo $this->headTitle() . PHP_EOL;
echo $this->headScript() . PHP_EOL;
?>
</head>
<body>
    <div id="header">
        <div id="logo"><a href="<?php echo $this->url(array(), 'home', true); ?>" title="На главную страницу"><img src="/images/owl.png" alt="sovia.ru" width="250" height="50" /></a></div>
    </div>
    <div id="navigation-main">
        <ul>
            <li><a href="/" title="Блог проекта">Блог</a></li>
            <li><a href="/" title="Читать сны">Сны</a></li>
            <li><a href="/" title="Сонник">Сонник</a></li>
            <li><a href="/" title="Форум о снах">Форум</a></li>
            <li><a href="/" title="Информация о проекте">О проекте</a></li>
        </ul>
    </div>
    <div id="content">
<?php echo $this->layout()->content; ?>

    </div>
    <div id="footer">
        
    </div>
</body>
</html>