<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?php
    foreach ($this->list as $url) {
        echo "\t<url>\n";
        echo "\t\t<loc>{$this->escape($url['loc'])}</loc>\n";
        if (isset($url['lastmod'])) {
            echo "\t\t<lastmod>{$this->escape($url['lastmod'])}</lastmod>\n";
        }
        echo "\t</url>\n";
    }
    ?>
</urlset>