<h1>Статистика по символам снов</h1>
<h2>Страница <?php echo $this->page; ?></h2>

<?php if (!empty($this->entries)) { ?>
<ul>
<?php
    /** @var $tag Posting_Tag_Row */
    foreach ($this->entries as $tag) {
    ?>
    <li><a href="<?php echo $this->url(array('tag' => $tag->getName()), 'dreams_tagged', true); ?>"><?php echo $this->escape($tag->getName()); ?></a> (<?php echo Ext_Helper_Declension::decline($tag->getWeight(), $this->words); ?>)</li>
    <?php
    }
?>
</ul>
<?php } else { ?>
    <div class="result">Данных нет</div>
<?php } ?>

<?php echo $this->paginator; ?>