<h1>Личный кабинет</h1>
<p>Выберите раздел</p>
<ul>
    <li><a href="<?php echo $this->url(array(), 'cabinet_profile', true); ?>">Мой профиль</a></li>
    <li><a href="<?php echo $this->url(array(), 'cabinet_avatars', true); ?>">Аватары</a></li>
    <li><a href="<?php echo $this->url(array(), 'cabinet_dreams', true); ?>">Мои сны</a></li>
    <li><a href="<?php echo $this->url(array(), 'cabinet_symbols', true); ?>">Мои символы снов</a></li>
</ul>