<h1>Произошла ошибка</h1>
<h2><?php echo $this->message ?></h2>
<p>Если вы&nbsp;считаете, что&nbsp;здесь есть какое-то недоразумение, свяжитесь
с&nbsp;администрацией ресурса.</p>

<?php if (isset($this->exception)): ?>

<h3>Исключение:</h3>
<p>
  <b>Сообщение:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Трейс:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Параметры запроса:</h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>

<?php endif ?>