<div id="auth-info">
<?php
if ($this->user->getId() > 0) {
	$login = $this->user->getLogin(false);
	$link  = $this->partial('user/_userlink.phtml', array('login' => $login));
?>
    <div id="auth-options">
        <div class="userpic"><?php echo ($this->user->getDefaultAvatar()); ?></div>
        <div class="fl">
            <p>Здравствуйте,<br /><?php echo $link; ?>.</p>
            <ul>
                <li><a href="/my/">Кабинет</a></li>
                <li><a href="/user/logout/">Выйти</a></li>
            </ul>
        </div>
    </div>
<?php
} else {
?>
    <form id="auth-top" method="post" action="<?php echo $this->url(array(), 'user_login', true); ?>">
    <dl>
        <dt><label for="auth-login-top">Вход на сайт: </label></dt>
        <dd><input type="text" size="16" maxlength="16" id="auth-login-top" name="login" title="Логин" /></dd>
        <dd><input type="password" size="14" id="auth-password-top" name="password" title="Пароль" /></dd>
        <dd><input type="image" src="/images/auth-submit.gif" id="auth-submit-top" title="Войти" /><input type="hidden" name="remember" value="1" /></dd>
    </dl>
    </form>
    <ul id="auth-options">
        <li><a href="<?php echo $this->url(array(), 'user_register', true); ?>">Регистрация</a></li>
        <li><a href="<?php echo $this->url(array(), 'user_forgot', true); ?>">Забыли пароль?</a></li>
    </ul>
<?php
}
?>
</div>
