<h1>Вход</h1>
<p>Для входа на сайт укажите свои логин и пароль.</p>
<ul>
    <li><a href="<?php echo $this->url(array(), 'user_register', true); ?>" title="Зарегистрироваться">Зарегситрироваться</a></li>
    <li><a href="<?php echo $this->url(array(), 'user_forgot', true); ?>" title="Сброс пароля">Я не помню пароль</a></li>
</ul>
<?php if (!empty($this->error)): ?>
<div class="error"><?php echo $this->error; ?></div>
<?php endif; ?>
<form action="<?php echo $this->url(); ?>" method="post">
<dl>
    <dt><label for="login">Логин</label></dt>
    <dd><input id="login" name="login" type="text" size="30" maxlength="100" /></dd>
    <dt><label for="password">Пароль</label></dt>
    <dd><input id="password" name="password" type="password" size="30" /></dd>
</dl>
<div class="submit"><button type="submit">Войти</button></div>
</form>
