<h1>Архив снов</h1>
<?php
if ($this->years->count()) {
?>
<div class="blog-archive">
    <?php echo $this->partial('posting/_archiveYears.phtml', array('years' => $this->years, 'route' => 'dreams_archive_year')); ?>
</div>
<?php
}
if (!empty($this->monthPosts)) {
    echo "<h2>{$this->year} год</h2>\n";
    echo $this->partial('posting/_archiveMonths.phtml', array('year' => $this->year, 'posts' => $this->monthPosts, 'months' => $this->months, 'route' => 'dreams_archive_month'));
}
if (!empty($this->posts)) {
    echo "<h2>{$this->month} {$this->year} года</h2>\n";
    echo $this->partial('posting/_entryDescription.phtml', array('entries' => $this->posts));
}
?>