<header>Чаще всего снится</header>
<nav>
    <ul>
        <?php
        foreach ($this->tags as $tag) {
            /** @var $tag Posting_Tag_Row */
            ?>
            <li>
                <a href="<?php echo $this->url(array('tag' => $tag->getName()), 'dreams_tagged', true); ?>"><?php echo $this->escape($tag->getName()); ?></a>
                (<?php echo Ext_Helper_Declension::decline($tag->getWeight(), $this->words); ?>)
            </li>
            <?php
        }
        ?>
    </ul>
</nav>
