<h1>Дневник снов</h1>
<h2>Сны с меткой «<?php echo $this->escape($this->tag); ?>», страница <?php echo $this->page; ?></h2>

<?php if ($this->canAdd) { ?>
<p><a href="<?php echo $this->url(array(), 'dreams_new', true); ?>" title="Добавить сон">Описать сон</a></p>
<?php } ?>

<?php echo $this->partial('posting/_entries.phtml', array('entries' => $this->entries)); ?>

<?php echo $this->paginator; ?>