<?php
echo $this->doctype() . PHP_EOL;
?>
<html>
<head>
<?php
echo $this->headMeta() . PHP_EOL;
echo $this->headLink() . PHP_EOL;
echo $this->headTitle() . PHP_EOL;
echo $this->headScript() . PHP_EOL;
?>
</head>
<body>
    <div id="header">
        <div id="logo"><a href="<?php echo $this->url(array(), 'home', true); ?>" title="На главную страницу"><img src="/images/owl.png" alt="sovia.ru" width="250" height="50" /></a></div>
    </div>
    <ul id="navigation-main">
        <li><a href="/" title="Блог проекта">Блог</a></li>
        <li><a href="<?php echo $this->url(array(), 'dreams', true); ?>" title="Читать сны">Сны</a></li>
        <li><a href="/" title="Сонник">Сонник</a></li>
        <li><a href="<?php echo $this->url(array(), 'forum', true); ?>" title="Форум о снах">Форум</a></li>
        <li><a href="<?php echo $this->url(array(), 'about', true); ?>" title="Информация о проекте">О проекте</a></li>
    </ul>
    <div id="content">
<?php
    echo $this->partial('flashMessage.phtml', array('message' => $this->flashMessage));
?>
<?php echo $this->layout()->content; ?>

    </div>

    <div id="right-column">
<?php
	echo $this->action('authinfo', 'User');
?>
        <div class="blocks">
            <div class="stat"></div>
            <div class="random-dream"></div>
            <div class="more">
                <p>А ещё есть вот что</p>
                <ul>
                    <li><a href="<?php echo $this->url(); ?>">Архив снов</a></li>
                    <li><a href="<?php echo $this->url(array(), 'dreams_random', true); ?>">Случайный сон</a></li>
                    <li><a href="<?php echo $this->url(); ?>">Описания сущностей</a></li>
                    <li><a href="<?php echo $this->url(); ?>">Бредовый генератор снов</a></li>
                </ul>
            </div>
            <div class="sape"></div>
        </div>
    </div>
    
    <div id="footer">
        <div class="footer-element">&#0169; 2006&#0150;2012 sovia.ru</div>
        <div class="footer-element"><a href="<?php echo $this->url(array(), 'tos', true); ?>" title="Пользовательское соглашение">Пользовательское соглашение</a></div>
    </div>
</body>
</html>