<?php
echo $this->doctype() . PHP_EOL;
?>
<html>
<head>
<?php
$this->sape(array(2, 1, 2));
echo $this->headMeta() . PHP_EOL;
echo $this->headLink() . PHP_EOL;
echo $this->headTitle() . PHP_EOL;
echo $this->headScript() . PHP_EOL;
?>
<!--[if lt IE 9]>
    <script type="text/javascript">
        document.createElement("nav");
        document.createElement("header");
        document.createElement("footer");
        document.createElement("section");
        document.createElement("aside");
        document.createElement("article");
    </script>
<![endif]-->
</head>
<body>
    <header id="page-header">
        <div><a href="<?php echo $this->url(array(), 'home', true); ?>" title="На главную страницу"><img src="/images/owl.png" alt="sovia.ru" width="250" height="50" /></a></div>
        <nav>
            <ul>
                <li><a href="<?php echo $this->url(array(), 'articles', true); ?>" title="Статьи и блог проекта">Статьи</a></li>
                <li><a href="<?php echo $this->url(array(), 'dreams', true); ?>" title="Читать сны">Сны</a></li>
                <li><a href="<?php echo $this->url(array(), 'dreambook', true); ?>" title="Сонник">Сонник</a></li>
                <li><a href="<?php echo $this->url(array(), 'forum', true); ?>" title="Форум о снах">Форум</a></li>
                <li><a href="<?php echo $this->url(array(), 'about', true); ?>" title="Информация о проекте">О проекте</a></li>
            </ul>
        </nav>
    </header>

    <section id="content">
<?php
    echo $this->partial('flashMessage.phtml', array('message' => $this->flashMessage));
?>
<?php echo $this->layout()->content; ?>

<?php
$chunk = $this->sape();
if (!empty($chunk)) {
    ?>
    <aside class="sape"><header>Реклама</header><?php echo $chunk ?></aside>
    <?php
}
?>

    </section>

    <section id="right-column">
<?php
	echo $this->action('authinfo', 'User');
?>
        <aside><?php echo $this->action('statistics', 'Dreams'); ?></aside>
        <aside><?php echo $this->action('sidebar', 'Dreams'); ?></aside>
        <aside>
            <header>А ещё есть вот что</header>
            <ul>
                <li><a href="<?php echo $this->url(array(), 'dreams_archive', true); ?>">Архив снов</a></li>
                <li><a href="<?php echo $this->url(array(), 'dreams_random', true); ?>">Случайный сон</a></li>
                <li><a href="<?php echo $this->url(array(), 'entities', true); ?>">Описания сущностей</a></li>
                <li><a href="<?php echo $this->url(array(), 'fun_rave', true); ?>">Бредовый генератор снов</a></li>
            </ul>
        </aside>
        <aside class="sape"><header>Реклама</header><?php echo $this->sape(); ?></aside>
    </section>
    
    <footer id="page-footer">
        <div><?php echo $this->partial('counters.phtml'); ?></div>
        <div>&#0169; 2006–2012 sovia.ru</div>
        <div><a href="<?php echo $this->url(array(), 'tos', true); ?>" title="Пользовательское соглашение">Пользовательское соглашение</a></div>
        <aside>
            <?php echo $this->sape('all'); ?>
        </aside>
    </footer>
</body>
</html>