<h1>Форум</h1>
<h2><?php echo $this->escape($this->community->getTitle()); ?></h2>
<?php
if (count($this->ancestors)) {
?>
    <div class="ancestors">Уровни выше:
<?php
    foreach ($this->ancestors as $ancestor) {
        $id = (strlen($ancestor['alias']) > 0) ? $ancestor['alias'] : $ancestor['id'];
?>
    <span><a href="<?php echo $this->url(array('id' => $id), 'forum_community', true); ?>"><?php echo $this->escape($ancestor['title']); ?></a></span>
<?php
    }
?>
    </div>
<?php
}
?>
<?php if (count($this->list)) { ?>
<h3>Сообщества внутри</h3>
<?php 	echo $this->partial('forum/communityList.phtml', array('list' => $this->list)); ?>
<?php } ?>
<?php   if ($this->entries->count() > 0): ?>
<div class="entries-list">
<?php
            foreach ($this->entries as $entry):
               echo $this->partial('posting/_entry.phtml', array('entry' => $this->entries->current()));
            endforeach;
?>
</div>
<?php   else: ?>
<div class="message">Записей нет</div>
<?php   endif; ?>
<?php echo $this->paginator; ?>
