<h1>Форум</h1>

<?php if (!empty($this->community)) { ?>
<h2>
    <?php $title = $this->escape($this->community->getTitle()); ?>
    <?php if ($this->link) { ?>
        <a href="<?php echo $this->url(array('id' => $this->community->getId()), 'forum_community', true); ?>"><?php echo $title ?></a>
    <?php } else { ?>
        <?php echo $title; ?>
    <?php } ?>
</h2>
<?php } ?>

<?php if (!empty($this->ancestors)) { ?>
<div class="ancestors">Уровни выше:
    <?php foreach ($this->ancestors as $ancestor) {
        $id = (strlen($ancestor['alias']) > 0) ? $ancestor['alias'] : $ancestor['id'];
        ?>
        <span><a href="<?php echo $this->url(array('id' => $id), 'forum_community', true); ?>"><?php echo $this->escape($ancestor['title']); ?></a></span>
    <?php } ?>
</div>
<?php } ?>
