<?php
if (!empty($this->list)) {
?>
<table class="community-list">
<?php
	if (!empty($this->caption)) {
?>
<caption><?php echo $this->caption; ?></caption>
<?php
	}
?>
<thead>
	<tr><th>Название</th><th>Записей</th></tr>
</thead>
<tbody>
<?php
	$row = 0;
	$format  = "\t<tr class=\"row%d\">\n";
	$format .= "\t\t<td>%s<a href=\"%s\">%s</a></td>";
	$format .= "<td>%d</td>\n\t</tr>\n";
    /** @var $community Posting_Community_Row */
	foreach ($this->list as $community) {
		if ($row++ > 1) {
			$row = 0;
		}
		$lock = '&nbsp;';
		if ($community->getIsInternal() > 0) {
			$lock  = '<div class="lock-' . $community->getIsInternal() . '">';
			$lock .= '&nbsp;</div>';
		}
		$link  = $this->url(array('id' => $community->getLink()), 'forum_community', true);
		$name  = $community->getTitle();
		$posts = $community->getHasPosts();
		printf($format, $row, $lock, $link, $name, $posts);
	}
?>
</tbody>
</table>
<div class="divider"></div>
<?php
}
?>