<?php echo $this->partial('forum/_header.phtml', array('community' => $this->community, 'ancestors' => $this->ancestors, 'link' => false)); ?>

<?php if (count($this->list)) { ?>
<h3>Сообщества внутри</h3>
<?php 	echo $this->partial('forum/communityList.phtml', array('list' => $this->list)); ?>
<?php } ?>

<?php echo $this->partial('posting/_entries.phtml', array('entries' => $this->entries)); ?>

<?php echo $this->paginator; ?>