<?php echo $this->partial('forum/_header.phtml', array('community' => $this->community, 'ancestors' => $this->ancestors, 'link' => false)); ?>

<?php if (count($this->list)) { ?>
<h3>Сообщества внутри</h3>
<?php 	echo $this->partial('forum/communityList.phtml', array('list' => $this->list)); ?>
<?php } ?>
<?php   if ($this->entries->count() > 0): ?>
<div class="entries-list">
<?php
            foreach ($this->entries as $entry):
               echo $this->partial('posting/_entryPreview.phtml', array('entry' => $this->entries->current(), 'route' => 'forum_entry'));
            endforeach;
?>
</div>
<?php   else: ?>
<div class="message">Записей нет</div>
<?php   endif; ?>
<?php echo $this->paginator; ?>
